# This file is a template, and might need editing before it works on your project.
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

pages:
  script:
    - npm install lerna
    - npm run setup
    - npm run build
    - npm run build-storybook
  artifacts:
    paths:
      - storybook-static
  only:
    - master
